# Generated by Django 5.2.3 on 2025-07-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentariocontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='comentariocontacto',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario Contacto', 'verbose_name_plural': 'Comentarios Contactos'},
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
